services:
  web:
    build: .
    command:
      sh -c "python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app                          # для dev: код с хоста
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf          #(есть в nginx/Dockerfile)
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web
    restart: unless-stopped

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped


  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  celery:
    build: .
    command: celery -A config worker -l INFO -P eventlet
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db
    restart: unless-stopped

  celery-beat:
    build: .
    command: celery -A config beat -l INFO -S django
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db
    restart: unless-stopped


volumes:
  pg_data:
  static_volume:
  media_volume:
