# Generated by Django 5.2.4 on 2025-07-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.PositiveIntegerField(
                help_text="Укажите время на выполнение привычки в секундах", verbose_name="Время на выполнение"
            ),
        ),
    ]
